### ISSUE TITLE
Add continuous integration to verify tests

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/kotlin-test-runner#28]
A Github Actions workflow should be added to verify that the tests pass. See https://github.com/exercism/prolog-test-runner/blob/main/.github/workflows/ci.yml for an example.

Linked to https://github.com/exercism/kotlin-test-runner/issues/27

**Comment by andsus** [comment]
Hello Erik,
How may I start working on this issue?

**Comment by ErikSchierboom** [comment]
@andsus You could do two things:

1. Update the Kotlin tests in https://github.com/exercism/kotlin-test-runner/blob/main/src/test/kotlin/exercism/kotlin/autotests/runner/report/SerializationKtTest.kt
2. Create a new `tests` directory with some "golden tests" (input/output combination). See https://github.com/exercism/prolog-test-runner/tree/main/tests for an example.

I feel like the second option might be nice, as you can copy things from other tracks:

- Create a `tests` folder
- Add five folders within the `tests` folder for different types of inputs: https://github.com/exercism/prolog-test-runner/tree/main/tests (note: you need to change the contents of the directory to match the Kotlin exercises (see https://github.com/exercism/kotlin/tree/main/exercises)
- Add `bin/run-tests.sh` and `bin/run-tests-in-dockers.sh` scripts that run the test runner on the folders in the `tests` folder (see https://github.com/exercism/prolog-test-runner/tree/main/bin for an example)
- Create a workflow to verify the tests https://github.com/exercism/prolog-test-runner/blob/main/.github/workflows/ci.yml 

Let me know if you have any questions.

**Comment by andsus** [comment]
@ErikSchierboom 
## All right,
- Will do number 2
- Will fork kotlin-test-runner
- Will create tests folder plus 5 folders with the content
- Will follow the rest of directions

**Comment by ErikSchierboom** [comment]
Perfect!

**Comment by andsus** [comment]
@ErikSchierboom 
I'm new to the process, so bear with me:

- I noticed the prolog test runner use leap-year as example. 
- Is there a convention which exercise to use? 

### Regarding expected_result.json:
- The approach to get expected_result.json for these 5 scenario:

1.  example-all-fail/
2.  example-empty-file/
3. example-partial-fail
4.  example-success/
5. example-syntax-error
Run the gradle test for those 5 scenario and capture output and save to expected_results.json ?

Thanks

**Comment by ErikSchierboom** [comment]
> I noticed the prolog test runner use leap-year as example.
> Is there a convention which exercise to use?

There isn't. You can choose any exercise you'd like, as long as it has the correct exercise structure.

> Run the gradle test for those 5 scenario and capture output and save to expected_results.json ?

I think you have to use the test runner itself. You can do that via `./bin/run.sh <slug> <path-to-exercise-dir> <path-to-exercise-dir>` (obviously replacing the placeholders). Once you've run that, you should a `results.json` in the passed in directory, which you can copy to `expected_results.json`.

**Comment by andsus** [comment]
Okay got it.

**Comment by andsus** [comment]
@ErikSchierboom 

Can you check what is the next step is? 
Completed all steps, but got failed gh action failure:
[action failure](url) https://github.com/andsus/kotlin-test-runner/runs/4128818284?check_suite_focus=true
[kotlin test runner](https://github.com/andsus/kotlin-test-runner)

Thanks

**Comment by andsus** [comment]
@ErikSchierboom 
- I've updated Dockerfile and GH action runner seems to be working:
- https://github.com/andsus/kotlin-test-runner/runs/4129711252?check_suite_focus=true

**Comment by ErikSchierboom** [comment]
@andsus I see that you've copied the `bin/run-tests.sh` and `bin/run-tests-in-docker.sh` into the Docker image, but they should actually not be included in the Docker image. Their sole purpose is to run things from the command-line, not to run within the test runner.

Regarding https://github.com/andsus/kotlin-test-runner/blob/main/.github/workflows/ci.yml#L22, I'd only run the tests in Docker. Running them without Docker will only cause them to be executed twice, and our main interest is in verifying that the Docker image works as intended.

**Comment by homersimpsons** [comment]
Looks like this can be closed with #36
